create table if not exists budget (
    id serial primary key,
    user_name_id int,
    home_loan_payment int,
    rental_loan_payment int,
    car_loan_payment int,
    land_loan_payment int,
    stocks_loan_payment int,
    boat_loan_payment int,
    recreational_vehicles_loan_payment int,
    pokemon_cards_loan_payment int,
    credit_card_loan_payment int,
    student_debt_loan_payment int, 
    medical_expenses_payment int,
    home_car_insurance_payment int,
    Utilities_payment int,
    cable_payment int,
    phone_payment int,
    entertainment_payment int,
    food_payment int,
    clothing_payment int,
    vehicle_maintenance_payment int,
    home_maintenance_payment int,
    internet_payment int, 
    dinner_payment int
)